# Generated by Django 5.2.1 on 2025-06-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='diretor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='filme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('atores', models.ManyToManyField(blank=True, related_name='filmes', to='filmes.ator')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmes.diretor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmes.genero')),
            ],
        ),
    ]
